package com.Manipulus.arctic.job.model;

import com.Manipulus.arctic.location.model.Location;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.Date;


@Entity
@Table(name = "job")
public class Job implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false, updatable = false)
    private long id; // The ID of the job, autogenerated by the database.

    @OneToOne
    @JoinColumn(name = "job_location")
    private Location location; // The customer associated with the job.

    @Column(name = "job_type")
    private String job_type; // The type of the job.

    @Column(name = "job_date")
    private Date job_date; // The date when the job was created.

    @Column(name = "job_status")
    private String job_status; // The status of the job.

    @Column(nullable = false, updatable = false)
    private String jobCode; // A unique code assigned to the job.

    public String getJobCode() {
        return jobCode;
    }

    public void setJobCode(String customerCode) {
        this.jobCode = customerCode;
    }
    // Default constructor for the Job class.
    public Job() {

    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }




    public String getJob_type() {
        return job_type;
    }

    public com.Manipulus.arctic.location.model.Location getLocation() {
        return location;
    }

    public void setLocation(com.Manipulus.arctic.location.model.Location location) {
        this.location = location;
    }

    public void setJob_type(String job_type) {
        this.job_type = job_type;
    }

    public Date getJob_date() {
        return job_date;
    }

    public void setJob_date(Date job_date) {
        this.job_date = job_date;
    }

    public String getJob_status() {
        return job_status;
    }

    public void setJob_status(String job_status) {
        this.job_status = job_status;
    }
    // Constructor for the Job class that takes in all the attributes.

    public Job(com.Manipulus.arctic.location.model.Location location, String job_type, Date job_date, String job_status, String jobCode) {
        this.location = location;
        this.job_type = job_type;
        this.job_date = job_date;
        this.job_status = job_status;
        this.jobCode = jobCode;
    }

    @Override
    public String toString() {
        return "Job{" +
                "id=" + id +
                ", location=" + location +
                ", job_type='" + job_type + '\'' +
                ", job_date=" + job_date +
                ", job_status='" + job_status + '\'' +
                ", jobCode='" + jobCode + '\'' +
                '}';
    }
}