package com.Manipulus.arctic.location.model;

import jakarta.persistence.*;
import java.io.Serializable;
import com.Manipulus.arctic.customer.model.Customer;

@Entity
@Table(name = "location")
public class Location implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false, updatable = false)
    private long id; // The ID of the location, autogenerated by the database.

    @ManyToOne(cascade = CascadeType.REMOVE)
    @JoinColumn(name = "location_customer")
    private Customer location_customer; // The status of the location.

    @Column(name = "location_lat")
    private Double location_lat; // The type of the location.

    @Column(name = "location_lng")
    private Double location_lng; // The date when the location was created.

    @Column(name = "location_title")
    private String location_title;

    @Column(nullable = false, updatable = false)
    private String locationCode; // A unique code assigned to the location.

    public String getlocationCode() {
        return locationCode;
    }

    public void setlocationCode(String customerCode) {
        this.locationCode = customerCode;
    }
    // Default constructor for the location class.
    public Location() {
    }

    public Location(Customer location_customer, Double location_lat, Double location_lng, String location_title, String locationCode) {
        this.location_customer = location_customer;
        this.location_lat = location_lat;
        this.location_lng = location_lng;
        this.location_title = location_title;
        this.locationCode = locationCode;
    }

    public String getLocation_title() {
        return location_title;
    }

    public void setLocation_title(String location_title) {
        this.location_title = location_title;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Double getLocation_lat() {
        return location_lat;
    }

    public void setLocation_lat(Double location_lat) {
        this.location_lat = location_lat;
    }

    public Double getLocation_lng() {
        return location_lng;
    }

    public void setLocation_lng(Double location_lng) {
        this.location_lng = location_lng;
    }

    public Customer getLocation_customer() {
        return location_customer;
    }

    public void setLocation_customer(Customer location_customer) {
        this.location_customer = location_customer;
    }


    @Override
    public String toString() {
        return "Location{" +
                "id=" + id +
                ", location_customer=" + location_customer +
                ", location_lat=" + location_lat +
                ", location_lng=" + location_lng +
                ", location_title=" + location_title +
                ", locationCode='" + locationCode + '\'' +
                '}';
    }
}